# Generated by Django 2.2.6 on 2019-11-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191116_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_name', models.CharField(max_length=255, verbose_name='作品名')),
                ('picture', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'Contents',
            },
        ),
        migrations.AlterField(
            model_name='reviews',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contents', verbose_name='作品名'),
        ),
        migrations.DeleteModel(
            name='ContentsList',
        ),
    ]
