# Generated by Django 2.2.6 on 2019-11-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191118_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='contents_name',
            field=models.CharField(max_length=255, verbose_name='作品画像'),
        ),
    ]
