# Generated by Django 2.2.6 on 2019-11-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191118_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='detail',
            field=models.CharField(max_length=100, null=True, verbose_name='詳細'),
        ),
    ]
