# Generated by Django 2.2.6 on 2019-11-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contents_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='detail',
            new_name='details',
        ),
    ]
