# Generated by Django 2.2.6 on 2019-11-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191120_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='contents_detail',
            field=models.TextField(null=True, verbose_name='詳細'),
        ),
    ]
