# Generated by Django 2.2.6 on 2019-11-27 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_recommend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommend',
            new_name='rating',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
    ]
