# Generated by Django 2.2.6 on 2019-11-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191127_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
