# Generated by Django 2.2.6 on 2019-11-28 00:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20191128_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rating',
            new_name='review_rating',
        ),
        migrations.AlterModelTable(
            name='review_rating',
            table='review_rating',
        ),
    ]
