# Generated by Django 2.2.6 on 2019-11-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20191128_0924'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review_rating',
            table='review_ratings',
        ),
    ]
