# Generated by Django 2.2.6 on 2019-11-28 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_auto_20191128_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_ratings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(verbose_name='rating')),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contents', verbose_name='作品名')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名')),
            ],
            options={
                'db_table': 'review_rating',
            },
        ),
        migrations.DeleteModel(
            name='review_rating',
        ),
    ]
